development:
  adapter: postgresql
  encoding: unicode
  database: apphoster_dev

test:
  adapter: postgresql
  encoding: unicode
  database: apphoster_test

production:
  adapter: sqlite3
  database: db/production.sqlite3
  pool: 5
  timeout: 5000
